# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest



steps:


- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'sonarAKS'
    scannerMode: 'CLI'
    configMode: 'file'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: SonarQubeAnalyze@4

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
